services:
  parcel-backend:
    image: ghcr.io/sadid205/parcel-backend:latest
    ports:
      - "5001:5000"
    env_file:
      - ./.env.production
    depends_on:
      - parcel-mongodb
    restart: unless-stopped
    networks:
      - parcel-network

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 400M
  parcel-frontend:
    image: ghcr.io/sadid205/parcel-frontend:latest
    ports:
      - "4176:80"
    depends_on:
      - parcel-backend
    restart: unless-stopped
    networks:
      - parcel-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 400M
  parcel-mongodb:
    image: mongo:7
    ports:
      - "27017"
    volumes:
      - mongo_data:/data/db
    env_file:
      - ./.env.production
    restart: unless-stopped
    networks:
      - parcel-network

    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 400M
  parcel-redis:
    image: redis:7-alpine
    container_name: parcel_redis
    ports:
      - "6379"
    volumes:
      - redis_data:/data
    env_file:
      - ./.env.production
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo_data:
  redis_data:

networks:
  parcel-network:
    driver: bridge
