# Stage 1: Build Stage
FROM node:20-alpine AS build-stage

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

FROM node:20-alpine AS production-stage

WORKDIR /app

ENV NODE_ENV=production

COPY package*.json ./

RUN npm ci --only=production

COPY --from=build-stage /app/dist ./dist

EXPOSE 5000

CMD ["node", "dist/server.js"]